### PR TITLE
italian translation fix

### PR DESCRIPTION
**Pull request by sound-code**

### CODE REVIEW

**Comment by emanuelschuetze** [comment]
Is this typo already fixed upstream in http://archive.tinymce.com/i18n/ ?

**Comment by sound-code** [comment]
it's not, I've checked

**Comment by emanuelschuetze** [comment]
Ok, then please fix it there, too! Our repo is just a clone of the upstream translations.

**Comment by sound-code** [comment]
well, I  dont know how to do it..

**Comment by emanuelschuetze** [comment]
see upstream issue for Italian translation typo: https://github.com/tinymce/tinymce/issues/1951

I added also the wish to create an official tinymce-i18n repo: see https://github.com/tinymce/tinymce/issues/3059

**Comment by emanuelschuetze** [comment]
I'll merge your fix here, but tinymce has to add this fix also upstream in transifex.

**Comment by sound-code** [comment]
ok

**Pull request merged**
